version: '3.8'
services:
  db:
    container_name: blind-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blind-db
    ports:
      - '5432:5432'
#    volumes:
#      - resource/db:/var/lib/postgresql/data
  app:
    container_name: blind-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: on-failure
    environment:
      - DATABASE_HOST=blind-db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=blind-db
      - DATABASE_PORT=5432
    depends_on:
      - db
#volumes:
#  db:
#    driver: local