logging:
  level:
    com: info

server:
  port: 8081

spring:
  # Database information
  datasource:
    url: jdbc:postgresql://localhost:5432/blind-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: postgres
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  output:
    ansi:
      enabled: always